#include "words_data.hpp"

namespace cmc {
namespace words {

const std::vector<WordInfo>& word_infos() {
    static const std::vector<WordInfo> table = {
        {
            "oga",
            "oga",
            "Talking",
            "Say something on the screen.",
            "oga <thing>",
            "`oga` is how a CMC program talks to you. Everything after it gets printed on one line, with spaces between the things.\n\nYou can `oga` numbers, text, piles, `gronk`, `nork`, `plop`, and boxes. A box shows what is *inside* it.",
            "oga \"Hello cave!\"\n\ngrunk name = \"Ugg\"\noga \"Hi\", name, \"you are\", 3, \"years old\"",
            {"print", "say"},
            {"oga <thing>, <thing>, <thing>"},
            {"`oga` with nothing after it prints an empty line.", "Quotes make text. `oga hi` looks for a box named `hi`; `oga \"hi\"` prints the word."},
            {"goop", "blorp", "unga"},
            0,
            0,
            false,
        },
        {
            "blorp",
            "blorp",
            "Talking",
            "Ask the user a question and get their answer as text.",
            "blorp \"What is your name?\"",
            "`blorp` shows a question and waits for the person to type an answer. The answer comes back as text (goop).\n\nIn OGABOOGA CODER a friendly question window pops up. In the terminal the person types into the console.",
            "grunk name = blorp \"What is your name?\"\noga \"Ooga\", name, \"!\"",
            {"ask"},
            {"blorp()"},
            {"The answer is always text, even if it looks like a number. Use a number box if you need math.", "You can blorp with no question: `grunk answer = blorp()`"},
            {"grunk", "goop", "oga"},
            0,
            0,
            false,
        },
        {
            "grunk",
            "grunk",
            "Boxes",
            "Make a box and put something in it.",
            "grunk <name> = <thing>",
            "A *box* remembers something for later. `grunk` makes a new box.\n\nBox names are made of letters, numbers, and `_`, and they cannot start with a number. `grunk x = 5` makes a box named `x` holding 5.\n\nTo put something new into a box that already exists, just write `x = 6` without `grunk`. That is called *changing* the box.",
            "grunk age = 4\ngrunk name = \"Ugg\"\noga name, \"is\", age\n\nage = age + 1   ugg a year passed\noga name, \"is now\", age",
            {"let", "make"},
            {},
            {"Using `grunk` again on the same name makes a fresh box (the old thing is forgotten).", "Changing a box that was never made says OOGA! -- make it first."},
            {"oga", "clump", "plop"},
            0,
            0,
            false,
        },
        {
            "binga",
            "binga",
            "Choices",
            "Do something only when a check is gronk.",
            "binga <check>\n    <things to do>\nunga",
            "`binga` asks a yes/no question and only does the things inside when the answer is `gronk` (true).\n\nUse `wonga` to say what to do when it is not gronk. Use `wonga binga` to check something else first, like 'else if'.\n\nEvery `binga` needs its own `unga` at the end.",
            "grunk apples = 3\n\nbinga apples > 2\n    oga \"That is a lot of apples!\"\nwonga\n    oga \"Just a few apples.\"\nunga",
            {"if"},
            {"binga <check>\n    <things>\nwonga\n    <other things>\nunga", "binga <check>\n    <things>\nwonga binga <check2>\n    <more>\nunga"},
            {"Checks use `==`, `!=`, `<`, `>`, `<=`, `>=`.", "You can stick checks together with `and`, `or`, and `not`."},
            {"wonga", "unga", "gronk", "nork", "and", "or", "not"},
            0,
            0,
            false,
        },
        {
            "wonga",
            "wonga",
            "Choices",
            "What to do when the binga check was not gronk.",
            "binga <check>\n    <things>\nwonga\n    <other things>\nunga",
            "`wonga` lives inside a `binga`. The things after it happen only when the `binga` check was `nork` (false).\n\n`wonga binga` checks something else before giving up.",
            "grunk door = \"open\"\n\nbinga door == \"open\"\n    oga \"Walk in!\"\nwonga\n    oga \"Knock first.\"\nunga",
            {"else"},
            {"wonga binga <check2>   ugg check something else"},
            {"`wonga` never has its own `unga`; the `unga` belongs to the whole `binga`."},
            {"binga", "unga"},
            0,
            0,
            false,
        },
        {
            "unga",
            "unga",
            "Choices",
            "Close a block of code.",
            "unga",
            "`unga` means 'that block is done'. Every `binga`, `booga`, `zug`, `zoop`, and `clump` block ends with `unga`.\n\nThink of it like a cave door closing behind the things you put inside.",
            "booga 3\n    oga \"unga!\"\nunga",
            {"end", "done", "finish"},
            {},
            {"Blocks can live inside blocks. Each one needs its own `unga`.", "An extra `unga` with nothing open makes a friendly OOGA! error."},
            {"binga", "booga", "zug", "zoop", "clump"},
            0,
            0,
            false,
        },
        {
            "booga",
            "booga",
            "Loops",
            "Do something again and again, a set number of times.",
            "booga <count>\n    <things to do>\nunga",
            "`booga 5` does the things inside five times.\n\nThe count must be a number. `booga 0` does nothing.\n\nInside the loop there is a magic box named `lap` that remembers which lap you are on: 1 for the first lap, 2 for the second, and so on.",
            "booga 3\n    oga \"BOOGA!\"\nunga\n\noga \"done\"",
            {"repeat"},
            {},
            {"Use the magic box `lap` to do different things each time: `oga \"lap\", lap`.", "For 'keep going until something changes' use `zug`."},
            {"zug", "zoop", "unga"},
            0,
            0,
            false,
        },
        {
            "zug",
            "zug",
            "Loops",
            "Keep doing something while a check stays gronk.",
            "zug <check>\n    <things to do>\nunga",
            "`zug` checks before every lap. If the check is `gronk`, it does the things inside and checks again.\n\nWhen the check becomes `nork`, the loop stops.",
            "grunk fuel = 3\n\nzug fuel > 0\n    oga \"Zoom! fuel left:\", fuel\n    fuel = fuel - 1\nunga\n\noga \"Out of fuel.\"",
            {"while"},
            {},
            {"If the check never becomes nork you get the 'ran for a very long time' error.", "Change a box inside the loop so the check can finish."},
            {"booga", "zoop", "unga"},
            0,
            0,
            false,
        },
        {
            "zoop",
            "zoop",
            "Loops",
            "Do something once for each thing in a pile or text.",
            "zoop <name> in <pile or text>\n    <things to do>\nunga",
            "`zoop` walks through a pile (or the letters of a text) one item at a time. The box you name holds the item for that lap.",
            "grunk pets = snorf(\"dog\", \"cat\", \"rock\")\n\nzoop pet in pets\n    oga \"I love my\", pet\nunga",
            {"for"},
            {},
            {"For text, each lap gives you one letter.", "The loop box is a normal box: you can oga it, do math with it, and so on."},
            {"snorf", "booga", "zug"},
            0,
            0,
            false,
        },
        {
            "clump",
            "clump",
            "Clumps",
            "Make your own word that does a bunch of things.",
            "clump <name>(<boxes>)\n    <things to do>\nunga",
            "A `clump` is a bunch of code with a name. Run it any time by writing its name with parentheses.\n\nThe names in parentheses become boxes filled with whatever you pass in. Use `ork` to give an answer back.",
            "clump yell(word)\n    oga shout(word), \"!!!\"\nunga\n\nyell(\"hello\")\nyell(\"booga\")",
            {"fn", "function", "def"},
            {"clump <name>()          ugg no boxes", "clump <name>(a, b, c)   ugg many boxes"},
            {"Make a clump before you use it (the computer reads top to bottom).", "A clump with an `ork` gives something back: `grunk x = double(4)`", "A clump that uses itself is called recursion -- powerful and fun."},
            {"ork", "unga", "grunk"},
            0,
            0,
            false,
        },
        {
            "ork",
            "ork",
            "Clumps",
            "Give an answer back from a clump.",
            "ork <thing>",
            "`ork` hands a value back to whoever called the clump and stops the clump right there.\n\nA clump without `ork` gives back `plop` (nothing).",
            "clump double(n)\n    ork n * 2\nunga\n\noga double(21)",
            {"return", "give"},
            {},
            {"`ork` with nothing after it gives back `plop`.", "`ork` outside of a clump is an OOGA! error."},
            {"clump", "plop"},
            0,
            0,
            false,
        },
        {
            "skrib",
            "skrib",
            "Drawing",
            "Draw on the picture window (OGABOOGA CODER's Draw tab).",
            "skrib circle <x>, <y>, <r>",
            "`skrib` (caveman for *scribble*) draws on the picture. The spot `0, 0` is the top-left corner. `x` goes right, `y` goes down.\n\nColors can be names like `\"red\"`, `\"blue\"`, `\"gold\"` or hex colors like `\"#ff8800\"`.",
            "skrib size 400, 400\nskrib color \"orange\"\nskrib circle 200, 200, 100\nskrib color \"black\"\nskrib dot 200, 200, 10\nskrib write \"SUN!\", 175, 320",
            {"draw"},
            {"skrib dot <x>, <y>, <r>      ugg filled circle", "skrib line <x1>, <y1>, <x2>, <y2>", "skrib box <x>, <y>, <w>, <h> ugg outline rectangle", "skrib blob <x>, <y>, <w>, <h> ugg filled rectangle", "skrib write \"words\", <x>, <y>", "skrib color \"red\"            ugg names or \"#ff8800\"", "skrib size <w>, <h>          ugg picture size", "skrib clear                  ugg wipe the picture"},
            {"The picture window opens by itself the first time you draw.", "Use `wait(ms)` between drawings to make a simple animation.", "In the terminal build, close the picture window when the program is done."},
            {"wait", "booga", "munga"},
            0,
            0,
            false,
        },
        {
            "ugg",
            "ugg",
            "Notes",
            "A note for humans. The computer ignores it.",
            "ugg <anything at all>",
            "`ugg` starts a note (comment). Everything after it on that line is ignored by the computer.\n\nNotes are how you explain your code to future-you.",
            "ugg this whole line is a note\noga \"hi\"   ugg this note comes after code",
            {"comment"},
            {},
            {"Notes do not slow the program down at all."},
            {},
            0,
            0,
            false,
        },
        {
            "and",
            "and",
            "Logic",
            "Gronk only when both sides are gronk.",
            "<check> and <check>",
            "`and` joins two checks. The answer is `gronk` only when both sides are gronk.",
            "grunk age = 7\n\nbinga age > 4 and age < 10\n    oga \"You are a big kid!\"\nunga",
            {},
            {},
            {"`and` stops early if the left side is nork."},
            {"or", "not", "binga"},
            0,
            0,
            false,
        },
        {
            "or",
            "or",
            "Logic",
            "Gronk when at least one side is gronk.",
            "<check> or <check>",
            "`or` joins two checks. The answer is `gronk` when either side is gronk.",
            "grunk day = \"sunday\"\n\nbinga day == \"saturday\" or day == \"sunday\"\n    oga \"No school!\"\nunga",
            {},
            {},
            {"`or` stops early if the left side is gronk."},
            {"and", "not", "binga"},
            0,
            0,
            false,
        },
        {
            "not",
            "not",
            "Logic",
            "Flip gronk to nork and nork to gronk.",
            "not <check>",
            "`not` flips a check. `not gronk` is `nork`.",
            "grunk hungry = nork\n\nbinga not hungry\n    oga \"Then let us go play!\"\nunga",
            {},
            {},
            {"Double flip: `not not gronk` is `gronk` again."},
            {"and", "or", "gronk", "nork"},
            0,
            0,
            false,
        },
        {
            "in",
            "in",
            "Loops",
            "Am I inside this pile / text?  Also used by zoop.",
            "<thing> in <pile or text>",
            "`in` asks: does this pile contain that thing? For text it asks about smaller pieces of text.\n\n`in` is also the little word inside every `zoop` loop.",
            "grunk pets = snorf(\"dog\", \"cat\")\n\nbinga \"cat\" in pets\n    oga \"There is a cat in the pile!\"\nunga",
            {},
            {"zoop <name> in <pile> ... unga"},
            {"`not in` works too: `binga \"fish\" not in pets`"},
            {"zoop", "snorf"},
            0,
            0,
            false,
        },
        {
            "gronk",
            "gronk",
            "Values",
            "The truth value for YES.",
            "gronk",
            "`gronk` means yes/on/true. It is what checks give back when they are happy.",
            "grunk light_on = gronk\noga light_on   ugg prints gronk",
            {"true"},
            {},
            {"`oga gronk` prints the word gronk."},
            {"nork", "binga"},
            0,
            0,
            false,
        },
        {
            "nork",
            "nork",
            "Values",
            "The truth value for NO.",
            "nork",
            "`nork` means no/off/false.",
            "grunk light_on = nork\nbinga not light_on\n    oga \"It is dark in here.\"\nunga",
            {"false"},
            {},
            {"Numbers can be truthy too: 0 is like nork, other numbers are like gronk."},
            {"gronk", "binga"},
            0,
            0,
            false,
        },
        {
            "plop",
            "plop",
            "Values",
            "Nothing at all. An empty spot.",
            "plop",
            "`plop` is the value of nothing. A clump without `ork` gives back `plop`. A fresh empty box holds `plop`.\n\nThere is also the pile helper `plop(pile, thing)` -- see its page.",
            "grunk treasure = plop\noga treasure   ugg prints: plop",
            {"nothing", "none"},
            {},
            {"`plop` is a fine way to say 'no answer yet'."},
            {"ork", "grunk", "plop_call"},
            0,
            0,
            false,
        },
        {
            "pi",
            "pi",
            "Values",
            "The circle number, about 3.14159.",
            "pi",
            "`pi` is the magic number of circles. It is already there, ready to use.",
            "oga \"A circle with radius 2 has around area\", pi * 2 * 2",
            {},
            {},
            {"It is really 3.141592653589793 -- CMC remembers the rest."},
            {"root", "round"},
            0,
            0,
            false,
        },
        {
            "snorf",
            "snorf",
            "Piles",
            "Make a pile of things.",
            "snorf(<thing>, <thing>, ...)",
            "`snorf` builds a *pile* (a list). Piles keep things in order and can grow and shrink.\n\nA pile can hold any mix of things: numbers, text, even other piles.",
            "grunk pets = snorf(\"dog\", \"cat\", \"rock\")\noga pets\noga nom(pets)   ugg how many",
            {},
            {},
            {"`snorf()` makes an empty pile.", "Spot numbers start at 0: the first thing is `pets[0]`."},
            {"nom", "skoop", "yoink", "plop_call", "zoop"},
            0,
            99,
            true,
        },
        {
            "plop_call",
            "plop",
            "Piles",
            "Plop a thing onto the end of a pile.",
            "plop(<pile>, <thing>)",
            "`plop(pile, thing)` adds a thing to the end of a pile.\n\nThe same word `plop` by itself means *nothing* -- this is the doing version.",
            "grunk bag = snorf()\nplop(bag, \"apple\")\nplop(bag, \"rock\")\noga bag",
            {},
            {},
            {"A pile grows as big as you like. Keep plopping!"},
            {"snorf", "yoink", "nom"},
            2,
            2,
            true,
        },
        {
            "nom",
            "nom",
            "Piles",
            "How many things? (length of a pile or text)",
            "nom(<pile or text>)",
            "`nom` counts. For a pile it counts the things. For text it counts the letters.",
            "grunk word = \"cave\"\noga nom(word)      ugg 4\n\ngrunk xs = snorf(1, 2, 3)\noga nom(xs)        ugg 3",
            {},
            {},
            {"Empty pile: nom is 0. Empty text \"\": nom is 0."},
            {"snorf", "skoop", "goop"},
            1,
            1,
            true,
        },
        {
            "skoop",
            "skoop",
            "Piles",
            "Scoop out one thing from a pile or text by its spot number.",
            "skoop(<pile or text>, <spot>)",
            "`skoop(pile, 2)` gives you the thing at spot 2. Spots start at 0.\n\n`pile[2]` does exactly the same thing. Negative spots count from the end: `-1` is the last thing.",
            "grunk pets = snorf(\"dog\", \"cat\", \"fish\")\noga skoop(pets, 0)   ugg dog\noga pets[2]          ugg fish\noga pets[-1]         ugg fish too",
            {},
            {},
            {"Asking for a spot that is not there gives an OOGA! error."},
            {"snorf", "nom", "yoink"},
            2,
            2,
            true,
        },
        {
            "yoink",
            "yoink",
            "Piles",
            "Take the last thing off a pile.",
            "yoink(<pile>)",
            "`yoink(pile)` removes the last thing and hands it back to you, like pulling the top rock off a stack.",
            "grunk stack = snorf(1, 2, 3)\ngrunk top = yoink(stack)\noga \"I yoinked\", top\noga stack   ugg [1, 2]",
            {},
            {},
            {"Yoinking an empty pile gives a friendly OOGA! error."},
            {"plop_call", "snorf", "nom"},
            1,
            1,
            true,
        },
        {
            "goop",
            "goop",
            "Text",
            "Squish anything into text.",
            "goop(<thing>)",
            "`goop` turns a number, pile, truth, or plop into text (a string).\n\nThis is how you stick numbers and words together: `\"I am \" + goop(7)`.",
            "grunk age = 7\noga \"I am \" + goop(age) + \" years old\"",
            {},
            {},
            {"`oga` already goops things for you. `goop` is for joining."},
            {"oga", "shout", "whisper", "split", "join"},
            1,
            1,
            true,
        },
        {
            "shout",
            "shout",
            "Text",
            "Make text ALL CAPS.",
            "shout(<text>)",
            "`shout(text)` turns every letter big: `shout(\"hi\")` is `\"HI\"`.",
            "oga shout(\"hello cave\")",
            {},
            {},
            {"Alien caves: `shout` only knows the letters it knows."},
            {"whisper", "goop"},
            1,
            1,
            true,
        },
        {
            "whisper",
            "whisper",
            "Text",
            "Make text all small letters.",
            "whisper(<text>)",
            "`whisper(text)` turns every letter small.",
            "oga whisper(\"SHHH VERY LOUD\")",
            {},
            {},
            {"Shout then whisper to make text calm again."},
            {"shout", "goop"},
            1,
            1,
            true,
        },
        {
            "flip",
            "flip",
            "Text",
            "Turn text backwards.",
            "flip(<text>)",
            "`flip(text)` turns the text around: `flip(\"cave\")` is `\"evac\"`.",
            "oga flip(\"booga\")   ugg agoob",
            {},
            {},
            {"flip works on any text, even one letter."},
            {"goop", "nom"},
            1,
            1,
            true,
        },
        {
            "find",
            "find",
            "Text",
            "Where does a smaller text start inside a bigger text?",
            "find(<text>, <piece>)",
            "`find(text, piece)` gives the spot number where `piece` starts inside `text`, or `-1` when it is not there at all.",
            "grunk word = \"caveman\"\noga find(word, \"man\")   ugg 4\noga find(word, \"z\")     ugg -1",
            {},
            {},
            {"Spots start at 0, so the first letter is spot 0."},
            {"skoop", "split", "nom"},
            2,
            2,
            true,
        },
        {
            "split",
            "split",
            "Text",
            "Chop text into a pile of pieces.",
            "split(<text>, <separator>)",
            "`split(text, \",\")` cuts text wherever the separator is and gives back a pile of the pieces.",
            "grunk words = split(\"rock,paper,scissors\", \",\")\noga words\noga nom(words)",
            {},
            {},
            {"Split on a space to get words: split(sentence, \" \")"},
            {"join", "snorf", "nom"},
            2,
            2,
            true,
        },
        {
            "join",
            "join",
            "Text",
            "Stick a pile of things together into one text.",
            "join(<pile>, <separator>)",
            "`join(pile, \"-\")` turns a pile into one text, putting the separator between the items.",
            "grunk xs = snorf(\"a\", \"b\", \"c\")\noga join(xs, \" + \")   ugg a + b + c",
            {},
            {},
            {"Numbers get gooped automatically."},
            {"split", "snorf", "goop"},
            2,
            2,
            true,
        },
        {
            "what",
            "what",
            "Text",
            "Ask what kind of thing something is.",
            "what(<thing>)",
            "`what` gives back a word: `\"number\"`, `\"text\"`, `\"truth\"`, `\"pile\"`, or `\"plop\"`.",
            "oga what(3)        ugg number\noga what(\"hi\")     ugg text\noga what(snorf())  ugg pile",
            {},
            {},
            {"Telling apart numbers and text is a very useful trick."},
            {"goop", "nom"},
            1,
            1,
            true,
        },
        {
            "munga",
            "munga",
            "Numbers",
            "Magic random number between two numbers.",
            "munga(<low>, <high>)",
            "`munga(1, 6)` gives a random whole number from 1 to 6 -- both ends included. Perfect for dice and games.\n\n`munga(1, 1)` is always 1, which is handy for testing.",
            "grunk dice = munga(1, 6)\noga \"You rolled a\", dice",
            {},
            {},
            {"Run the program again for a different number."},
            {"round", "small", "big", "skrib"},
            2,
            2,
            true,
        },
        {
            "numba",
            "numba",
            "Numbers",
            "Turn text into a number.",
            "numba(<text>)",
            "`blorp` always gives back text, even when someone types `7`. `numba(\"7\")` turns that text into a real number so math works.\n\nIt also cleans up extra spaces people type.",
            "grunk answer = blorp \"Pick a number!\"\ngrunk n = numba(answer)\noga n, \"plus one is\", n + 1",
            {},
            {},
            {"If the text is not a number, numba says OOGA! with a kind hint.", "A number passed to numba comes back unchanged."},
            {"blorp", "goop", "what", "round"},
            1,
            1,
            true,
        },
        {
            "round",
            "round",
            "Numbers",
            "Make a decimal into the closest whole number.",
            "round(<number>)",
            "`round(2.6)` is 3. `round(2.4)` is 2.",
            "oga round(2.6)\noga round(2.4)",
            {},
            {},
            {"`flat` always goes down, `roof` always goes up."},
            {"flat", "roof"},
            1,
            1,
            true,
        },
        {
            "flat",
            "flat",
            "Numbers",
            "Smash a decimal down to the whole number below it.",
            "flat(<number>)",
            "`flat(2.9)` is 2. It always goes down, like water.",
            "oga flat(2.9)\noga flat(2.0)",
            {},
            {},
            {"flat is also called 'floor' in other languages."},
            {"round", "roof"},
            1,
            1,
            true,
        },
        {
            "roof",
            "roof",
            "Numbers",
            "Lift a decimal up to the whole number above it.",
            "roof(<number>)",
            "`roof(2.1)` is 3. It always goes up, like a roof.",
            "oga roof(2.1)\noga roof(2.0)",
            {},
            {},
            {"roof is also called 'ceil' in other languages."},
            {"round", "flat"},
            1,
            1,
            true,
        },
        {
            "abs",
            "abs",
            "Numbers",
            "How far from zero? (make negative numbers positive)",
            "abs(<number>)",
            "`abs(-7)` is 7. `abs(7)` is 7. It measures distance from zero.",
            "oga abs(-7)\noga abs(3 - 10)",
            {},
            {},
            {"Great for finding how far apart two things are."},
            {"small", "big"},
            1,
            1,
            true,
        },
        {
            "small",
            "small",
            "Numbers",
            "The smaller of two numbers.",
            "small(<a>, <b>)",
            "`small(3, 9)` is 3.",
            "oga small(3, 9)",
            {},
            {},
            {"The opposite twin is `big`."},
            {"big", "abs"},
            2,
            2,
            true,
        },
        {
            "big",
            "big",
            "Numbers",
            "The bigger of two numbers.",
            "big(<a>, <b>)",
            "`big(3, 9)` is 9.",
            "oga big(3, 9)",
            {},
            {},
            {"Chain them: big(big(1, 5), 3) is 5."},
            {"small", "abs"},
            2,
            2,
            true,
        },
        {
            "root",
            "root",
            "Numbers",
            "The square root: what number times itself makes this?",
            "root(<number>)",
            "`root(9)` is 3. Negative numbers have no normal root, so CMC says OOGA!",
            "oga root(9)\noga root(2)",
            {},
            {},
            {"root(2) is a wiggly decimal -- `round` it if you like."},
            {"pow", "round", "pi"},
            1,
            1,
            true,
        },
        {
            "pow",
            "pow",
            "Numbers",
            "A number times itself many times.",
            "pow(<number>, <times>)",
            "`pow(2, 3)` is 2 * 2 * 2 = 8.",
            "oga pow(2, 3)\noga pow(10, 2)",
            {},
            {},
            {"pow(x, 2) is x squared."},
            {"root"},
            2,
            2,
            true,
        },
        {
            "wait",
            "wait",
            "Drawing",
            "Pause the program for some milliseconds.",
            "wait(<milliseconds>)",
            "`wait(1000)` pauses for one second. 1000 milliseconds = 1 second.\n\nWaiting between drawings makes animation: draw, wait, clear, draw again.",
            "skrib color \"red\"\nskrib dot 50, 50, 10\nwait(500)\nskrib clear\nskrib color \"blue\"\nskrib dot 100, 50, 10",
            {},
            {},
            {"The Stop button still works while waiting."},
            {"skrib", "booga"},
            1,
            1,
            true,
        },
    };
    return table;
}

const std::vector<std::string>& categories() {
    static const std::vector<std::string> table = {
        "Talking",
        "Boxes",
        "Choices",
        "Logic",
        "Loops",
        "Clumps",
        "Values",
        "Piles",
        "Text",
        "Numbers",
        "Drawing",
        "Notes",
    };
    return table;
}

}
}
