"""Write the repo docs that must never drift from the code.

Generates:
    docs/03_KEYWORD_DICTIONARY.md   from src/cmc/words.py
    docs/08_EXAMPLES_GALLERY.md     from examples/
And copies the wiki pages that should also live in docs/:
    docs/02_TUTORIAL_30_MINUTES.md
    docs/06_BLOCKS_GUIDE.md
    docs/07_DRAWING_GUIDE.md
    docs/10_CONTRIBUTING.md
    docs/12_GLOSSARY.md
    docs/13_FAQ.md
    CHEATSHEET.md
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "src"))

from cmc import words  # noqa: E402
from cmc.paths import examples_dir  # noqa: E402

DOCS = os.path.join(ROOT, "docs")
PAGES = os.path.join(ROOT, "site_content", "pages")

COPY_PLAN = [
    ("tutorial.md", "02_TUTORIAL_30_MINUTES.md"),
    ("cheatsheet.md", "../CHEATSHEET.md"),
    ("blocks-guide.md", "06_BLOCKS_GUIDE.md"),
    ("drawing.md", "07_DRAWING_GUIDE.md"),
    ("contributing.md", "10_CONTRIBUTING.md"),
    ("glossary.md", "12_GLOSSARY.md"),
    ("faq.md", "13_FAQ.md"),
]

INTRO = (
    "> This file is generated by `tools/write_docs.py` -- do not edit it by hand.\n"
    "> Edit `site_content/pages/{source}` and run the tool.\n\n"
)


CONCAT_PLAN = [
    (["roadmap.md", "changelog.md"], "11_ROADMAP_CHANGELOG.md"),
]


def copy_pages():
    for source, target in COPY_PLAN:
        with open(os.path.join(PAGES, source), "r", encoding="utf-8") as handle:
            text = handle.read()
        with open(os.path.join(DOCS, target), "w", encoding="utf-8") as handle:
            handle.write(INTRO.format(source=source) + text)
        print("wrote docs/" + target if not target.startswith("..") else "wrote " + target)
    for sources, target in CONCAT_PLAN:
        parts = []
        for source in sources:
            with open(os.path.join(PAGES, source), "r", encoding="utf-8") as handle:
                parts.append(handle.read())
        with open(os.path.join(DOCS, target), "w", encoding="utf-8") as handle:
            handle.write(INTRO.format(source=" + ".join(sources)) + "\n\n---\n\n".join(parts))
        print("wrote docs/" + target)


def write_dictionary():
    lines = [
        "# The CMC keyword dictionary",
        "",
        "Every word in the language with its meaning, syntax, example, and tips.",
        "The website version (with one page per word) lives in",
        "[`website/wiki/words.html`](../website/wiki/words.html).",
        "",
        "Words are grouped by what they do.",
        "",
    ]
    by_category = {}
    for word in words.all_words():
        by_category.setdefault(word["category"], []).append(word)

    lines.append("| Category | Words |")
    lines.append("| --- | --- |")
    for category in words.CATEGORIES:
        if category in by_category:
            names = ", ".join("`" + w["name"] + "`" for w in by_category[category])
            lines.append("| " + category + " | " + names + " |")
    lines.append("")

    for category in words.CATEGORIES:
        if category not in by_category:
            continue
        lines.append("## " + category)
        lines.append("")
        for word in by_category[category]:
            name = word.get("display", word["name"])
            header = "### `" + name + "`"
            if word.get("aliases"):
                header += " (english: " + ", ".join("`" + a + "`" for a in word["aliases"]) + ")"
            lines.append(header)
            lines.append("")
            lines.append("**" + word.get("summary", "") + "**")
            lines.append("")
            lines.append("```cmc")
            lines.append(word.get("syntax", ""))
            for extra in word.get("extra_syntax", []):
                lines.append(extra)
            lines.append("```")
            lines.append("")
            lines.append(word.get("doc", ""))
            lines.append("")
            lines.append("Example:")
            lines.append("")
            lines.append("```cmc")
            lines.append(word.get("example", ""))
            lines.append("```")
            lines.append("")
            if word.get("tips"):
                lines.append("Tips:")
                for tip in word["tips"]:
                    lines.append("- " + tip)
                lines.append("")
            if word.get("related"):
                lines.append("See also: " + ", ".join("`" + r + "`" for r in word["related"]))
                lines.append("")

    with open(os.path.join(DOCS, "03_KEYWORD_DICTIONARY.md"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print("wrote docs/03_KEYWORD_DICTIONARY.md")


def write_examples():
    folder = examples_dir()
    lines = [
        "# Examples gallery",
        "",
        "Every example program in the `examples/` folder, with its code and output.",
        "Generated by `tools/write_docs.py`.",
        "",
    ]
    names = sorted(f for f in os.listdir(folder) if f.endswith(".cmc"))
    for name in names:
        path = os.path.join(folder, name)
        with open(path, "r", encoding="utf-8") as handle:
            source = handle.read()
        lines.append("## `" + name + "`")
        lines.append("")
        for comment in source.splitlines():
            stripped = comment.strip()
            if stripped.startswith("ugg"):
                note = stripped[3:].strip()
                if note and not note.lower().startswith("no-check"):
                    lines.append("*" + note + "*")
                    lines.append("")
                break
        lines.append("```cmc")
        lines.append(source.rstrip())
        lines.append("```")
        out_path = os.path.splitext(path)[0] + ".out"
        if os.path.exists(out_path):
            with open(out_path, "r", encoding="utf-8") as handle:
                output = handle.read().rstrip()
            lines.append("")
            lines.append("Output:")
            lines.append("")
            lines.append("```text")
            lines.append(output)
            lines.append("```")
        in_path = os.path.splitext(path)[0] + ".in"
        if os.path.exists(in_path):
            with open(in_path, "r", encoding="utf-8") as handle:
                answers = handle.read().rstrip()
            lines.append("")
            lines.append("Answers typed by the person (one per `blorp` prompt):")
            lines.append("")
            lines.append("```text")
            lines.append(answers)
            lines.append("```")
        lines.append("")

    with open(os.path.join(DOCS, "08_EXAMPLES_GALLERY.md"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print("wrote docs/08_EXAMPLES_GALLERY.md")


if __name__ == "__main__":
    copy_pages()
    write_dictionary()
    write_examples()
    print("docs are fresh.")